### ISSUE TITLE
Error When Installing

### ISSUE THREAD

**Issue by aljawaid** [creecros/kbphpimap#6]
I got this when installing... site is down unless I delete the plugin
```
[php7:error] [pid 1182489] [client 86.189.166.135:58946] PHP Fatal error:  Uncaught Error: Class 'Kanboard\\Plugin\\Kbphpimap\\Action\\ConvertEmailToTask' not found in /var/www/my.domain/public_html/plugins/kbphpimap/Plugin.php:27\nStack trace:\n#0 /var/www/my.domain/public_html/app/Core/Plugin/Loader.php(127): Kanboard\\Plugin\\Kbphpimap\\Plugin->initialize()\n#1 /var/www/my.domain/public_html/app/Core/Plugin/Loader.php(67): Kanboard\\Core\\Plugin\\Loader->initializePlugin()\n#2 /var/www/my.domain/public_html/app/ServiceProvider/PluginProvider.php(27): Kanboard\\Core\\Plugin\\Loader->scan()\n#3 /var/www/my.domain/public_html/vendor/pimple/pimple/src/Pimple/Container.php(290): Kanboard\\ServiceProvider\\PluginProvider->register()\n#4 /var/www/my.domain/public_html/app/common.php(58): Pimple\\Container->register()\n#5 /var/www/my.domain/public_html/index.php(6): require('/var/www/my.domain')\n#6 {main}\n  thrown in /var/www/my.domain/public_html/plugins/kbphpimap/Plugin.php on line 27
```

**Comment by creecros** [comment]
make sure you capitalize "K" in plugin folder name
